### ISSUE TITLE
`models` cannot be received from props *and* context

### ISSUE THREAD

**Issue by spencer-brown** [mongodb-js/connect-backbone-to-react#14]
Based on the way `context` and `props` are handled [here](https://github.com/mongodb-js/connect-backbone-to-react/blob/8c7bff1afc1366e1c1a73434f109e115997aed55/lib/connect-backbone-to-react.js#L87), `models` cannot be received from `context` and `props` simultaneously. `props` gets priority, knocking out any `models` passed via `context`. We had a discussion at @mixmaxhq about this today and concluded that it would probably make more sense for models received from `context` and `props` to be merged, eg with

```js
const models = Object.assign({}, context.models, props.models);
```

~~~If we make this change, we'll also want to update how check received `models` [here](https://github.com/mongodb-js/connect-backbone-to-react/blob/8c7bff1afc1366e1c1a73434f109e115997aed55/lib/connect-backbone-to-react.js#L127).~~~ <-- I don't think this is necessary, actually.

---

I wanted to check in with y'all before submitting a PR to hear how this lines up with your usage. Does this change make sense to y'all too? If so, I'm happy to go ahead and make it!

Thanks!

**Comment by hswolff** [comment]
Yep I dig that! Especially having `props.models` take priority over `context` as you showed in your example. 

Super appreciate the thoughtful issue giving a heads up before hand as well. 

Please do submit a PR!
